# Generated by Django 3.2.12 on 2025-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('attendees', models.JSONField(default=list)),
            ],
        ),
    ]
